# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/aiocapsule',
                'doc_host': 'https://woncoh1.github.io',
                'git_url': 'https://github.com/woncoh1/aiocapsule',
                'lib_path': 'aiocapsule'},
  'syms': {'aiocapsule.core': {'aiocapsule.core.foo': ('core.html#foo', 'aiocapsule/core.py')}}}
